### ISSUE TITLE
Failed to run after successful installation

### ISSUE THREAD

**Issue by shenwei356** [Ebedthan/xgt#1]
**Describe the bug**

Examples do not work. No useful error info is available.

```
$ xgt search g__Escherichia
Error: There was an error making the request or receiving the response.

$ xgt genome GCA_001512625.1
Error: There was an error making the request or receiving the response.
```

**To Reproduce**

```
$ git clone https://github.com/Ebedthan/xgt.git
cd xgt

$ rustup update stable
  stable-x86_64-unknown-linux-gnu updated - rustc 1.80.0 (051478957 2024-07-21) (from rustc 1.71.1 (eb26296b5 2023-08-03)

# If default rust install directory is ~/.cargo
cargo install --path . --root ~/.cargo
xgt -h

```

**Desktop (please complete the following information):**
 - OS: Manjaro Linux `Linux mBio 6.6.41-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jul 19 14:57:10 UTC 2024 x86_64 GNU/Linux`

**Comment by Ebedthan** [comment]
Hello @shenwei356,
You should add the `-k/--insecure` option to disable peer SSL certificate verification as the GTDB API has some SSL issues.
It should then work.

**Comment by shenwei356** [comment]
Oh, I see now. Thanks!

Maybe it would be switched on by default.
